server:
  port: 8080

limit:
  read: 10000
  rate: 1000

smtp:
  host: ""
  port: ""
  username: 
  password: 
  from: 

upload:
  dir: 
  url_prefix: 

feature:
  enable_email_verify: 
  enable_markdown_api: 
